[package]
name = "tonic-reflection"
version = "0.1.0"
authors = ["James Nugent <james@jen20.com>"]
edition = "2018"
license = "MIT"
repository = "https://github.com/hyperium/tonic"
homepage = "https://github.com/hyperium/tonic"
description = """
Server Reflection module of `tonic` gRPC implementation.
"""
readme = "README.md"
categories = ["network-programming", "asynchronous"]
keywords = ["rpc", "grpc", "async", "reflection"]

[dependencies]
bytes = "0.5"
prost = "0.6"
prost-types = "0.6"
thiserror = "1"
tokio = { version = "0.2", features = ["sync", "stream"] }
tonic = { version = "0.2", path = "../tonic", features = ["codegen", "prost"] }

[build-dependencies]
tonic-build = { version = "0.2", path = "../tonic-build" }
